/**
 * bridge-database.types.ts — TypeScript interfaces matching the ambient.external_agents
 * and ambient.a2a_messages DB tables created in:
 * supabase/migrations/20260315000002_ambient_bridge_tables.sql
 */

export interface ExternalAgentRow {
  /** UUID primary key — generated by DB */
  id?: string;
  /** Multi-tenant isolation */
  org_slug: string;
  /** External agent logical identifier — unique per org */
  agent_id: string;
  name?: string | null;
  description?: string | null;
  url: string;
  version?: string | null;
  /** Cached .well-known/agent.json content */
  agent_card?: unknown | null;
  /** Array of capability IDs — stored as JSONB */
  capabilities?: string[] | null;
  /** Reputation score 0-100 */
  trust_score: number;
  /** Derived from trust_score */
  trust_level: 'unknown' | 'neutral' | 'trusted' | 'untrusted';
  interactions_count: number;
  status: 'online' | 'offline' | 'unknown';
  last_heartbeat?: string | null;
  /** Whether this agent origin is on the allowlist for inbound requests */
  allowed_origin: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface A2AMessageRow {
  /** UUID primary key — generated by DB */
  id?: string;
  /** Multi-tenant isolation */
  org_slug: string;
  /** inbound = external agent calling Bridge; outbound = Bridge calling external agent */
  direction: 'inbound' | 'outbound';
  /** ID of the external agent involved */
  external_agent_id?: string | null;
  /** JSON-RPC method name */
  method?: string | null;
  /** JSON-RPC request id */
  request_id?: string | null;
  /** Full JSON-RPC request body */
  request_payload?: unknown | null;
  /** Full JSON-RPC response body */
  response_payload?: unknown | null;
  /** Message lifecycle status */
  status: 'pending' | 'success' | 'error' | 'rejected' | 'rate_limited';
  /** Rejection reason when status is rejected or rate_limited */
  rejection_reason?: string | null;
  /** Round-trip duration in milliseconds */
  duration_ms?: number | null;
  created_at?: string;
}
