# syntax=docker/dockerfile:1
# Vite SPA — build from monorepo root, serve static files with nginx.
#
# Required build args:
#   TURBO_FILTER  e.g. @orchestratorai/platform-web
#   APP_DIR       e.g. apps/web
#
# Pass provider selectors and any VITE_* URLs via compose build.args (from .env).

ARG TURBO_FILTER
ARG APP_DIR

FROM node:22-bookworm-slim AS build
WORKDIR /app
ENV NO_UPDATE_NOTIFIER=1 \
    NPM_CONFIG_AUDIT=false \
    NPM_CONFIG_FUND=false \
    NPM_CONFIG_LOGLEVEL=error \
    NPM_CONFIG_UPDATE_NOTIFIER=false \
    TURBO_TELEMETRY_DISABLED=1
COPY package.json package-lock.json turbo.json ./
COPY packages ./packages
COPY apps ./apps
RUN npm ci --no-audit --fund=false --loglevel=error

# Shared provider selectors (validated in prod by several Vue entrypoints)
ARG VITE_AUTH_PROVIDER=supabase
ARG VITE_CONFIG_PROVIDER=local
ARG VITE_DB_PROVIDER=supabase_pg
ARG VITE_STORAGE_PROVIDER=supabase_storage
ARG VITE_WORK_PROVIDER=slack
ARG VITE_KNOWLEDGE_PROVIDER=none
ARG VITE_ENFORCE_HTTPS=false
ARG VITE_REQUIRE_SECURE_CONTEXT=false
ARG VITE_BASE_URL=/
ARG VITE_GATEWAY_MODE=
ARG VITE_MONOLITH_MODE=true

ENV VITE_BASE_URL=$VITE_BASE_URL \
    VITE_GATEWAY_MODE=$VITE_GATEWAY_MODE \
    VITE_MONOLITH_MODE=$VITE_MONOLITH_MODE \
    VITE_AUTH_PROVIDER=$VITE_AUTH_PROVIDER \
    VITE_CONFIG_PROVIDER=$VITE_CONFIG_PROVIDER \
    VITE_DB_PROVIDER=$VITE_DB_PROVIDER \
    VITE_STORAGE_PROVIDER=$VITE_STORAGE_PROVIDER \
    VITE_WORK_PROVIDER=$VITE_WORK_PROVIDER \
    VITE_KNOWLEDGE_PROVIDER=$VITE_KNOWLEDGE_PROVIDER \
    VITE_ENFORCE_HTTPS=$VITE_ENFORCE_HTTPS \
    VITE_REQUIRE_SECURE_CONTEXT=$VITE_REQUIRE_SECURE_CONTEXT

# Optional URLs passed from compose / .env.
ARG VITE_SUPABASE_URL=
ARG VITE_API_BASE_URL=
ARG VITE_API_NESTJS_BASE_URL=
ARG VITE_API_URL=
ARG VITE_MAIN_API_URL=
ARG VITE_API_PORT=
ARG VITE_DEMO_USER_EMAIL=
ARG VITE_DEMO_USER_PASSWORD=
ARG VITE_GOOGLE_CLIENT_ID=
ARG VITE_GOOGLE_REDIRECT_URI=

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_API_NESTJS_BASE_URL=$VITE_API_NESTJS_BASE_URL \
    VITE_API_URL=$VITE_API_URL \
    VITE_MAIN_API_URL=$VITE_MAIN_API_URL \
    VITE_API_PORT=$VITE_API_PORT \
    VITE_DEMO_USER_EMAIL=$VITE_DEMO_USER_EMAIL \
    VITE_DEMO_USER_PASSWORD=$VITE_DEMO_USER_PASSWORD \
    VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID \
    VITE_GOOGLE_REDIRECT_URI=$VITE_GOOGLE_REDIRECT_URI

ARG TURBO_FILTER
RUN npx turbo run build --filter="${TURBO_FILTER}"

FROM nginx:1.27-alpine
ARG APP_DIR
ARG NGINX_CONF=docker/nginx-spa.conf
COPY ${NGINX_CONF} /etc/nginx/conf.d/default.conf
COPY --from=build /app/${APP_DIR}/dist /usr/share/nginx/html
EXPOSE 80
