-- Repairs for migrations the deployment ledger adopted without running
-- (effort: migration-ledger-reconciliation). Each was checked against the
-- Studio by replaying it on the baseline and comparing what it changes.
-- Everything here is idempotent: on a database that ran the originals it
-- changes nothing.
BEGIN;

-- 20260724120000_add_database_change_stream: never ran. The PostgreSQL /
-- Cloud SQL change-stream provider reads this table and its capture function.
CREATE TABLE IF NOT EXISTS ambient.database_change_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schema_name TEXT NOT NULL,
  table_name TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('INSERT', 'UPDATE', 'DELETE')),
  new_record JSONB,
  old_record JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE ambient.database_change_events OWNER TO postgres;
CREATE INDEX IF NOT EXISTS database_change_events_created_at_idx
  ON ambient.database_change_events (created_at);
CREATE OR REPLACE FUNCTION ambient.capture_database_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ambient
AS $$
DECLARE
  change_id BIGINT;
BEGIN
  INSERT INTO ambient.database_change_events (
    schema_name,
    table_name,
    event_type,
    new_record,
    old_record
  )
  VALUES (
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    TG_OP,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN TO_JSONB(NEW) ELSE NULL END,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN TO_JSONB(OLD) ELSE NULL END
  )
  RETURNING id INTO change_id;
  PERFORM pg_notify('orchestratorai_database_changes', change_id::TEXT);
  RETURN COALESCE(NEW, OLD);
END;
$$;
ALTER FUNCTION ambient.capture_database_change() OWNER TO postgres;
COMMENT ON TABLE ambient.database_change_events IS
  'Provider-neutral database change events consumed by the database change-stream plane.';
COMMENT ON FUNCTION ambient.capture_database_change() IS
  'Captures row changes and notifies PostgreSQL/Cloud SQL database change-stream consumers.';

-- 20260728210000_add_secure_conversation_nonce_replay_protection: the table
-- existed (from the baseline), but row level security and its policy were
-- never applied, and the expiry index has another name here.
DO $$
BEGIN
  IF to_regclass('ambient.a2a_inbound_nonces_expires_at_idx') IS NULL
     AND to_regclass('ambient.ambient_a2a_inbound_nonces_expires_at_idx') IS NOT NULL THEN
    ALTER INDEX ambient.ambient_a2a_inbound_nonces_expires_at_idx RENAME TO a2a_inbound_nonces_expires_at_idx;
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS a2a_inbound_nonces_expires_at_idx
  ON ambient.a2a_inbound_nonces (expires_at);
ALTER TABLE ambient.a2a_inbound_nonces ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS service_role_all_a2a_inbound_nonces ON ambient.a2a_inbound_nonces;
CREATE POLICY service_role_all_a2a_inbound_nonces
  ON ambient.a2a_inbound_nonces
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- 20260922190000_fix_local_model_vendor ran, but local models the inventory
-- added later (it did not set vendor) came in without one. The inventory now
-- sets it; the column requires it from here on.
UPDATE public.llm_models SET vendor = 'ollama', updated_at = now()
WHERE provider_name = 'ollama' AND vendor IS NULL;
ALTER TABLE public.llm_models ALTER COLUMN vendor SET NOT NULL;

COMMIT;
