CREATE SCHEMA IF NOT EXISTS ambient;

CREATE TABLE IF NOT EXISTS ambient.database_change_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schema_name TEXT NOT NULL,
  table_name TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('INSERT', 'UPDATE', 'DELETE')),
  new_record JSONB,
  old_record JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS database_change_events_created_at_idx
  ON ambient.database_change_events (created_at);

CREATE OR REPLACE FUNCTION ambient.capture_database_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ambient
AS $$
DECLARE
  change_id BIGINT;
BEGIN
  INSERT INTO ambient.database_change_events (
    schema_name,
    table_name,
    event_type,
    new_record,
    old_record
  )
  VALUES (
    TG_TABLE_SCHEMA,
    TG_TABLE_NAME,
    TG_OP,
    CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN TO_JSONB(NEW) ELSE NULL END,
    CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN TO_JSONB(OLD) ELSE NULL END
  )
  RETURNING id INTO change_id;

  PERFORM pg_notify('orchestratorai_database_changes', change_id::TEXT);

  RETURN COALESCE(NEW, OLD);
END;
$$;

COMMENT ON TABLE ambient.database_change_events IS
  'Provider-neutral database change events consumed by the database change-stream plane.';

COMMENT ON FUNCTION ambient.capture_database_change() IS
  'Captures row changes and notifies PostgreSQL/Cloud SQL database change-stream consumers.';
