<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { useContentForgeStore } from '../../stores/content-forge.store';
import LoadingSpinner from '../../components/shared/LoadingSpinner.vue';
import EmptyState from '../../components/shared/EmptyState.vue';

const router = useRouter();
const store = useContentForgeStore();
const showGenerateForm = ref(false);
const topicInput = ref('');
const generateError = ref<string | null>(null);

onMounted(async () => {
  await store.fetchDrafts();
});

async function handleGenerate() {
  if (!topicInput.value) return;
  generateError.value = null;
  try {
    const draft = await store.generateDraft(topicInput.value);
    topicInput.value = '';
    showGenerateForm.value = false;
    router.push(`/apps/content-forge/drafts/${draft.id}`);
  } catch (e) {
    generateError.value = e instanceof Error ? e.message : String(e);
  }
}

function statusBadge(status: string): string {
  switch (status) {
    case 'draft': return 'bg-gray-700 text-gray-300';
    case 'review': return 'bg-yellow-900 text-yellow-300';
    case 'published': return 'bg-green-900 text-green-300';
    default: return 'bg-gray-700 text-gray-300';
  }
}
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-white">Drafts</h1>
        <p class="text-gray-400 text-sm mt-1">Content drafts generated by the multi-agent pipeline</p>
      </div>
      <button class="btn-primary" @click="showGenerateForm = !showGenerateForm">Generate Draft</button>
    </div>

    <div v-if="showGenerateForm" class="card">
      <div class="space-y-3">
        <div>
          <label class="block text-xs text-gray-400 mb-1">Topic</label>
          <input v-model="topicInput" type="text" placeholder="Enter a topic for content generation..." class="input-field w-full" />
        </div>
        <div class="flex gap-3">
          <button class="btn-primary text-sm" @click="handleGenerate">Generate</button>
          <button class="btn-secondary text-sm" @click="showGenerateForm = false">Cancel</button>
        </div>
        <p v-if="generateError" class="text-red-400 text-sm">{{ generateError }}</p>
      </div>
    </div>

    <div v-if="store.error" class="card border border-red-500 flex items-center justify-between gap-4">
      <p class="text-red-400 text-sm">{{ store.error }}</p>
      <button class="btn-secondary text-sm shrink-0" @click="store.fetchDrafts()">Retry</button>
    </div>

    <LoadingSpinner v-if="store.loading" label="Loading drafts..." />

    <EmptyState
      v-else-if="store.drafts.length === 0 && !store.error"
      title="No Drafts"
      message="No drafts yet. Click &quot;Generate Draft&quot; to create one from a topic."
      actionLabel="Create Draft"
      actionRoute="/apps/content-forge/drafts"
    />

    <div v-else class="space-y-3">
      <div
        v-for="draft in store.drafts"
        :key="draft.id"
        class="card cursor-pointer hover:border-protocol-primary transition-colors"
        @click="router.push(`/apps/content-forge/drafts/${draft.id}`)"
      >
        <div class="flex items-start justify-between">
          <div class="flex-1">
            <div class="flex items-center gap-2">
              <h3 class="text-sm font-medium text-gray-200">{{ draft.title }}</h3>
              <span :class="['text-xs px-2 py-0.5 rounded', statusBadge(draft.status)]">{{ draft.status }}</span>
            </div>
            <p class="text-xs text-gray-400 mt-1">{{ draft.sources.length }} sources</p>
          </div>
          <div class="text-right">
            <p class="text-xs text-gray-400">Updated: {{ new Date(draft.updatedAt).toLocaleString() }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
