-- Migration: Fix embedding model metadata and drop fixed-dimension vector column
--
-- Problem: Collections created before the EMBEDDING_SERVICE plane had embeddingModel
-- metadata that didn't match the actual embeddings (always Ollama nomic-embed-text at 768d).
-- The SQL Server embedding_vector column was VECTOR(768) which prevented multi-model support.
--
-- Fix:
-- 1. Update all collections that have stored chunks to use nomic-embed-text/768d
--    (matching the actual embeddings that were generated by the old Ollama-only code)
-- 2. Drop the embedding_vector column — we now use dynamic CAST from the NVARCHAR
--    embedding column at query time, supporting any dimension per collection.

-- SQL Server version:
-- UPDATE rag_data.rag_collections
-- SET embedding_model = 'nomic-embed-text', embedding_dimensions = 768
-- WHERE embedding_model != 'nomic-embed-text'
--   AND id IN (SELECT DISTINCT collection_id FROM rag_data.rag_document_chunks);
--
-- IF EXISTS (SELECT 1 FROM sys.columns
--   WHERE object_id = OBJECT_ID('rag_data.rag_document_chunks') AND name = 'embedding_vector')
--   ALTER TABLE rag_data.rag_document_chunks DROP COLUMN embedding_vector;

-- PostgreSQL / Supabase version (for local dev):
UPDATE rag_data.rag_collections
SET embedding_model = 'nomic-embed-text', embedding_dimensions = 768
WHERE embedding_model != 'nomic-embed-text'
  AND id IN (SELECT DISTINCT collection_id FROM rag_data.rag_document_chunks);
